/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recursion;

import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class ListGUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    AddressList list;

    public ListGUI() {
        list = new AddressList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        nameField = new javax.swing.JTextField();
        telField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        addToFrontButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        outputPane = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        dobLabel = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        addToRearButton = new javax.swing.JButton();
        reverseButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        isEmptyButton = new javax.swing.JButton();
        sizeButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchByBox = new javax.swing.JComboBox<>();
        revToStringButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        telField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telFieldActionPerformed(evt);
            }
        });

        addToFrontButton.setText("Add to Front");
        addToFrontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFrontButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("name");

        telLabel.setText("Tel no.");

        emailLabel.setText("E-mail");

        AddressLabel.setText("Address");

        outputArea.setColumns(20);
        outputArea.setRows(5);
        outputPane.setViewportView(outputArea);

        dobLabel.setText("D.O.B");

        dobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobFieldActionPerformed(evt);
            }
        });

        addToRearButton.setText("Add to Rear");
        addToRearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToRearButtonActionPerformed(evt);
            }
        });

        reverseButton.setText("Reverse");
        reverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        isEmptyButton.setText("is Empty?");
        isEmptyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isEmptyButtonActionPerformed(evt);
            }
        });

        sizeButton.setText("Size of List");
        sizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeButtonActionPerformed(evt);
            }
        });

        searchLabel.setText("search:");

        searchButton.setText("Search List");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "number by name", "email by name", "name by number", "date of birth by name" }));
        searchByBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByBoxActionPerformed(evt);
            }
        });

        revToStringButton.setText("rev toString");
        revToStringButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revToStringButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressField)
                    .addComponent(emailField)
                    .addComponent(telField)
                    .addComponent(dobField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobLabel)
                            .addComponent(telLabel)
                            .addComponent(emailLabel)
                            .addComponent(AddressLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(searchByBox, 0, 145, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addToFrontButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addToRearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reverseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(sizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(isEmptyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(revToStringButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel)
                    .addComponent(outputPane, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addToFrontButton, addToRearButton, isEmptyButton, printButton, reverseButton, sizeButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(searchByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addToFrontButton))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telLabel)
                                .addGap(10, 10, 10)
                                .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(emailLabel)
                                .addGap(10, 10, 10)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(AddressLabel)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sizeButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addToRearButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reverseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(printButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(isEmptyButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(dobLabel)
                                .addGap(10, 10, 10)
                                .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(revToStringButton))))
                    .addComponent(outputPane))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addToFrontButton, addToRearButton, addressField, dobField, emailField, isEmptyButton, nameField, printButton, reverseButton, sizeButton, telField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {searchButton, searchField});

    }// </editor-fold>//GEN-END:initComponents
    private boolean isFieldFilled() {
        boolean answer = false;
        if (nameField.getText() != "") {
            if (telField.getText() != "") {
                if (emailField.getText() != "") {
                    if (addressField.getText() != "") {
                        if (dobField.getText() != "") {
                            answer = true;
                        }
                    }
                }

            }
        }
        if(!answer)
            JOptionPane.showMessageDialog(this, "all not all fields filled");
        return answer;
    }
    private void addToFrontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFrontButtonActionPerformed
        if (isFieldFilled()) {
            list.addToFront(nameField.getText(), telField.getText(), emailField.getText(),
                    addressField.getText(), dobField.getText());
        }
    }//GEN-LAST:event_addToFrontButtonActionPerformed

    private void addToRearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToRearButtonActionPerformed
        if (isFieldFilled()) {
            list.addToBack(nameField.getText(), telField.getText(), emailField.getText(),
                    addressField.getText(), dobField.getText());
        }
    }//GEN-LAST:event_addToRearButtonActionPerformed

    private void reverseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseButtonActionPerformed
        list.reverse();
    }//GEN-LAST:event_reverseButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        outputArea.setText(list.toString());
    }//GEN-LAST:event_printButtonActionPerformed

    private void isEmptyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isEmptyButtonActionPerformed
        outputArea.setText(list.isEmpty()+"");
    }//GEN-LAST:event_isEmptyButtonActionPerformed

    private void sizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeButtonActionPerformed
        outputArea.setText(list.sizeOf()+"");
    }//GEN-LAST:event_sizeButtonActionPerformed

    private void telFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telFieldActionPerformed

    }//GEN-LAST:event_telFieldActionPerformed

    private void searchByBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByBoxActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (this.searchByBox.getSelectedItem().equals("number by name")) {
            this.outputArea.setText(list.phoneNumberByName(searchField.getText()));
        } else if (this.searchByBox.getSelectedItem().equals("email by name")) {
            this.outputArea.setText(list.emailByName(searchField.getText()));
        } else if (this.searchByBox.getSelectedItem().equals("name by number")) {
            this.outputArea.setText(list.nameByPhoneNumber(searchField.getText()));
        } else if (this.searchByBox.getSelectedItem().equals("date of birth by name")) {
            this.outputArea.setText(list.dobByName(searchField.getText()));
        } else {

        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobFieldActionPerformed

    private void revToStringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revToStringButtonActionPerformed
        outputArea.setText(list.reverseToString());
    }//GEN-LAST:event_revToStringButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JButton addToFrontButton;
    private javax.swing.JButton addToRearButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton isEmptyButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JScrollPane outputPane;
    private javax.swing.JButton printButton;
    private javax.swing.JButton revToStringButton;
    private javax.swing.JButton reverseButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchByBox;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton sizeButton;
    private javax.swing.JTextField telField;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables
}
