/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recursion;

import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    AddressList list;
    public NewJFrame() {
        list = new AddressList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButton = new javax.swing.JButton();
        addToFrontButton = new javax.swing.JButton();
        addToRearButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        reverseButton = new javax.swing.JButton();
        isEmptyButton = new javax.swing.JButton();
        sizeButton = new javax.swing.JButton();
        revToStringButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        telField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        searchByBox = new javax.swing.JComboBox<>();
        searchLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setText("Search List");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        addToFrontButton.setText("Add to Front");
        addToFrontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFrontButtonActionPerformed(evt);
            }
        });

        addToRearButton.setText("Add to Rear");
        addToRearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToRearButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        reverseButton.setText("Reverse");
        reverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseButtonActionPerformed(evt);
            }
        });

        isEmptyButton.setText("is Empty?");
        isEmptyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isEmptyButtonActionPerformed(evt);
            }
        });

        sizeButton.setText("Size of List");
        sizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeButtonActionPerformed(evt);
            }
        });

        revToStringButton.setText("rev toString");
        revToStringButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revToStringButtonActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        searchByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "number by name", "email by name", "name by number", "date of birth by name" }));

        searchLabel.setText("search:");

        nameLabel.setText("name:");

        telLabel.setText("Tel Number");

        emailLabel.setText("E-Mail");

        addressLabel.setText("Address");

        dobLabel.setText("Date of Birth");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telLabel)
                            .addComponent(emailLabel)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel)
                            .addComponent(addressLabel)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addToRearButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addToFrontButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(reverseButton))
                            .addComponent(sizeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isEmptyButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(printButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(revToStringButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addressField, dobField, emailField, jScrollPane1, nameField, searchByBox, searchField, telField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addToFrontButton, addToRearButton, isEmptyButton, printButton, revToStringButton, reverseButton, searchButton, sizeButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addToFrontButton)
                                .addGap(5, 5, 5)
                                .addComponent(addToRearButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reverseButton)
                                .addGap(5, 5, 5)
                                .addComponent(printButton)
                                .addGap(5, 5, 5)
                                .addComponent(isEmptyButton)
                                .addGap(5, 5, 5)
                                .addComponent(sizeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revToStringButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(5, 5, 5)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(telLabel)
                                .addGap(5, 5, 5)
                                .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(emailLabel)
                                .addGap(5, 5, 5)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(addressLabel)
                                .addGap(5, 5, 5)
                                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(dobLabel)))
                        .addGap(5, 5, 5)
                        .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addToFrontButton, addToRearButton, addressField, dobField, emailField, isEmptyButton, nameField, printButton, revToStringButton, reverseButton, searchButton, searchField, sizeButton, telField});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean isFieldFilled() {
        boolean answer = false;
        if (nameField.getText() != "") {
            if (telField.getText() != "") {
                if (emailField.getText() != "") {
                    if (addressField.getText() != "") {
                        if (dobField.getText() != "") {
                            answer = true;
                        }
                    }
                }

            }
        }
        if (!answer) {
            JOptionPane.showMessageDialog(this, "all not all fields filled");
        }
        return answer;
    }
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (this.searchByBox.getSelectedItem().equals("number by name")) {
            this.outputArea.setText(list.phoneNumberByName(searchField.getText()));
        } else if (this.searchByBox.getSelectedItem().equals("email by name")) {
            this.outputArea.setText(list.emailByName(searchField.getText()));
        } else if (this.searchByBox.getSelectedItem().equals("name by number")) {
            this.outputArea.setText(list.nameByPhoneNumber(searchField.getText()));
        } else if (this.searchByBox.getSelectedItem().equals("date of birth by name")) {
            this.outputArea.setText(list.dobByName(searchField.getText()));
        }
        System.out.println(searchByBox.getSelectedItem().toString());
    }//GEN-LAST:event_searchButtonActionPerformed

    private void addToRearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToRearButtonActionPerformed
        if (isFieldFilled()) {
            list.addToBack(nameField.getText(), telField.getText(), emailField.getText(),
                    addressField.getText(), dobField.getText());
        }
    }//GEN-LAST:event_addToRearButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void addToFrontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFrontButtonActionPerformed
        if (isFieldFilled()) {
            list.addToFront(nameField.getText(), telField.getText(), emailField.getText(),
                    addressField.getText(), dobField.getText());
        }
    }//GEN-LAST:event_addToFrontButtonActionPerformed

    private void reverseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseButtonActionPerformed
        list = list.reverse();
    }//GEN-LAST:event_reverseButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        outputArea.setText(list.toString());
    }//GEN-LAST:event_printButtonActionPerformed

    private void isEmptyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isEmptyButtonActionPerformed
        outputArea.setText(list.isEmpty() + "");
    }//GEN-LAST:event_isEmptyButtonActionPerformed

    private void sizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeButtonActionPerformed
        outputArea.setText(list.sizeOf() + "");
    }//GEN-LAST:event_sizeButtonActionPerformed

    private void revToStringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revToStringButtonActionPerformed
        outputArea.setText(list.reverseToString());
    }//GEN-LAST:event_revToStringButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToFrontButton;
    private javax.swing.JButton addToRearButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton isEmptyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JButton printButton;
    private javax.swing.JButton revToStringButton;
    private javax.swing.JButton reverseButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchByBox;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton sizeButton;
    private javax.swing.JTextField telField;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables
}
