package vendingmachine;

import java.awt.event.ActionEvent;

/**
 * Graphical User Interface for the Vending Machine Class
 *
 * @author Tevin Scott
 * @version 1.0
 */
public class GUI extends javax.swing.JFrame {

    private VendingMachine vmObj;
    private String adminField;
    private String changePrompt;
    private String reEnterPrompt;
    private boolean reEnter;

    /**
     * Creates new form VendingMachine
     */
    public GUI() {
        initComponents();
        this.
        vmObj = new VendingMachine();
        adminField = "";
        changePrompt = "Enter New PW";
        reEnterPrompt = "Re-Enter PW";
        reEnter = false;
        this.setPrices();
    }
    /**
     * sets the prices of the JButtons
     */
    private void setPrices(){
        cocaColaButton1.setText("$" + vmObj.getSelectedItemObj(0).getPricing());
        cocaColaButton2.setText("$" + vmObj.getSelectedItemObj(0).getPricing());
        cokeZeroButton1.setText("$" + vmObj.getSelectedItemObj(1).getPricing());
        cokeZeroButton2.setText("$" + vmObj.getSelectedItemObj(1).getPricing());
        dietCokeButton1.setText("$" + vmObj.getSelectedItemObj(2).getPricing());
        dietCokeButton2.setText("$" + vmObj.getSelectedItemObj(2).getPricing());
        spriteButton1.setText("$" + vmObj.getSelectedItemObj(3).getPricing());
        spriteButton2.setText("$" + vmObj.getSelectedItemObj(3).getPricing());
        poweradeButton.setText("$" + vmObj.getSelectedItemObj(4).getPricing());
        mtDewButton.setText("$" + vmObj.getSelectedItemObj(5).getPricing());
        vitaWaterButton.setText("$" + vmObj.getSelectedItemObj(6).getPricing());
        dasaniButton.setText("$" + vmObj.getSelectedItemObj(7).getPricing());
    }
    /**
     * adds input to the adminField at the end of the text
     * @param input 
     */
    private void addToField(String input){
        this.adminField = adminField + input;
    }
    /**
     * sets the admin display to the current quantity of the selected Item
     */
    private void setDisplayToQuantity(){
        adminField = "Quantity: " + vmObj.getSelectedItemQuantity();
        this.updateAdminDisplay();
    }
    /**
     * removes the last digit in the TextField
     */
    private void deleteFromField(){
        if(adminField.length() > 0)
            this.adminField = adminField.substring(0, adminField.length()-1);
        this.updateAdminDisplay();
    }
    /**
     * updates the adminDisplay field
     */
    private void updateAdminDisplay(){
        adminDisplay.setText(adminField);
    }
    /**
     * updates the coin value display
     */
    private void updateDisplay() {
        display.setText(vmObj.getTempStore() + "");
    }
    /**
     * clears adminTextField for newPassword change 
     */
    private void passwordChangeClear(){
        if(this.adminDisplay.getText().equals(changePrompt)){
            adminField = "";
        }
        if(this.adminDisplay.getText().equals(reEnterPrompt)){
            adminField = "";
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cocaColaButton1 = new javax.swing.JButton();
        cocaColaButton2 = new javax.swing.JButton();
        cokeZeroButton1 = new javax.swing.JButton();
        cokeZeroButton2 = new javax.swing.JButton();
        dietCokeButton1 = new javax.swing.JButton();
        dietCokeButton2 = new javax.swing.JButton();
        spriteButton1 = new javax.swing.JButton();
        spriteButton2 = new javax.swing.JButton();
        poweradeButton = new javax.swing.JButton();
        mtDewButton = new javax.swing.JButton();
        vitaWaterButton = new javax.swing.JButton();
        dasaniButton = new javax.swing.JButton();
        addDollar = new javax.swing.JButton();
        addQuartButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        adminButton = new javax.swing.JToggleButton();
        display = new javax.swing.JTextField();
        adminDisplay = new javax.swing.JTextField();
        numButton1 = new javax.swing.JButton();
        numButton2 = new javax.swing.JButton();
        numButton3 = new javax.swing.JButton();
        numButton4 = new javax.swing.JButton();
        numButton5 = new javax.swing.JButton();
        numButton6 = new javax.swing.JButton();
        numButton7 = new javax.swing.JButton();
        numButton8 = new javax.swing.JButton();
        numButton9 = new javax.swing.JButton();
        numButton0 = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine");

        jPanel1.setLayout(null);

        cocaColaButton1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        cocaColaButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cocaColaButton1.setBorderPainted(false);
        cocaColaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaColaButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(cocaColaButton1);
        cocaColaButton1.setBounds(340, 550, 40, 20);

        cocaColaButton2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        cocaColaButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cocaColaButton2.setBorderPainted(false);
        cocaColaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaColaButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(cocaColaButton2);
        cocaColaButton2.setBounds(390, 550, 40, 20);

        cokeZeroButton1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        cokeZeroButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cokeZeroButton1.setBorderPainted(false);
        cokeZeroButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeZeroButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(cokeZeroButton1);
        cokeZeroButton1.setBounds(450, 550, 40, 20);

        cokeZeroButton2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        cokeZeroButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cokeZeroButton2.setBorderPainted(false);
        cokeZeroButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeZeroButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(cokeZeroButton2);
        cokeZeroButton2.setBounds(510, 550, 40, 20);

        dietCokeButton1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        dietCokeButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dietCokeButton1.setBorderPainted(false);
        dietCokeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietCokeButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(dietCokeButton1);
        dietCokeButton1.setBounds(340, 640, 40, 20);

        dietCokeButton2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        dietCokeButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dietCokeButton2.setBorderPainted(false);
        dietCokeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietCokeButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(dietCokeButton2);
        dietCokeButton2.setBounds(390, 640, 40, 20);

        spriteButton1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        spriteButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spriteButton1.setBorderPainted(false);
        spriteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(spriteButton1);
        spriteButton1.setBounds(450, 640, 40, 20);

        spriteButton2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        spriteButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spriteButton2.setBorderPainted(false);
        spriteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(spriteButton2);
        spriteButton2.setBounds(510, 640, 40, 20);

        poweradeButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        poweradeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        poweradeButton.setBorderPainted(false);
        poweradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poweradeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(poweradeButton);
        poweradeButton.setBounds(340, 730, 40, 20);

        mtDewButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mtDewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mtDewButton.setBorderPainted(false);
        mtDewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtDewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mtDewButton);
        mtDewButton.setBounds(390, 730, 40, 20);

        vitaWaterButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        vitaWaterButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vitaWaterButton.setBorderPainted(false);
        vitaWaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitaWaterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(vitaWaterButton);
        vitaWaterButton.setBounds(450, 730, 40, 20);

        dasaniButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        dasaniButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dasaniButton.setBorderPainted(false);
        dasaniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasaniButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dasaniButton);
        dasaniButton.setBounds(510, 730, 40, 20);

        addDollar.setBackground(new java.awt.Color(51, 51, 51));
        addDollar.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        addDollar.setForeground(new java.awt.Color(255, 255, 255));
        addDollar.setText("$1");
        addDollar.setContentAreaFilled(false);
        addDollar.setOpaque(true);
        addDollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDollarActionPerformed(evt);
            }
        });
        jPanel1.add(addDollar);
        addDollar.setBounds(340, 430, 50, 20);

        addQuartButton.setBackground(new java.awt.Color(51, 51, 51));
        addQuartButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        addQuartButton.setForeground(new java.awt.Color(255, 255, 255));
        addQuartButton.setText("25¢");
        addQuartButton.setContentAreaFilled(false);
        addQuartButton.setOpaque(true);
        addQuartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuart(evt);
            }
        });
        jPanel1.add(addQuartButton);
        addQuartButton.setBounds(500, 410, 50, 40);

        returnButton.setBackground(new java.awt.Color(51, 51, 51));
        returnButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.setText("return");
        returnButton.setContentAreaFilled(false);
        returnButton.setOpaque(true);
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(returnButton);
        returnButton.setBounds(440, 420, 50, 30);

        adminButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        adminButton.setText("Admin Mode");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton);
        adminButton.setBounds(450, 10, 95, 24);

        display.setEditable(false);
        display.setBackground(new java.awt.Color(51, 0, 51));
        display.setFont(new java.awt.Font("Digital-7", 0, 18)); // NOI18N
        display.setForeground(new java.awt.Color(204, 0, 0));
        display.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        display.setText("0.00");
        jPanel1.add(display);
        display.setBounds(460, 380, 90, 30);

        adminDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(adminDisplay);
        adminDisplay.setBounds(460, 40, 90, 30);

        numButton1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton1.setText("1");
        numButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton1);
        numButton1.setBounds(460, 70, 30, 30);

        numButton2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton2.setText("2");
        numButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton2);
        numButton2.setBounds(490, 70, 30, 30);

        numButton3.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton3.setText("3");
        numButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton3);
        numButton3.setBounds(520, 70, 30, 30);

        numButton4.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton4.setText("4");
        numButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton4);
        numButton4.setBounds(460, 100, 30, 30);

        numButton5.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton5.setText("5");
        numButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton5);
        numButton5.setBounds(490, 100, 30, 30);

        numButton6.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton6.setText("6");
        numButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton6);
        numButton6.setBounds(520, 100, 30, 30);

        numButton7.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton7.setText("7");
        numButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton7);
        numButton7.setBounds(460, 130, 30, 30);

        numButton8.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton8.setText("8");
        numButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton8);
        numButton8.setBounds(490, 130, 30, 30);

        numButton9.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton9.setText("9");
        numButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton9);
        numButton9.setBounds(520, 130, 30, 30);

        numButton0.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        numButton0.setText("0");
        numButton0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(numButton0);
        numButton0.setBounds(490, 160, 30, 30);

        plusButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        plusButton.setText("+");
        plusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(plusButton);
        plusButton.setBounds(460, 160, 30, 30);

        minusButton.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        minusButton.setText("-");
        minusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(minusButton);
        minusButton.setBounds(520, 160, 30, 30);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vending machine.jpg"))); // NOI18N
        BackGround.setText("jLabel1");
        jPanel1.add(BackGround);
        BackGround.setBounds(-10, 0, 570, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * toggles the admin mode
     * @param evt 
     */
    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        if(!adminButton.isSelected()){
            vmObj.setAdminEnabled(false);
            adminDisplay.setText("Admin Disabled");
        }
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     * clears the coin balance and updates the display
     * @param evt
     */
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        vmObj.coinReturn();
        this.updateDisplay();
    }//GEN-LAST:event_returnButtonActionPerformed
    /**
    * adds 7 to the adminDisplay
    * @param evt 
    */
    private void numButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton7ActionPerformed
        this.passwordChangeClear();
        this.addToField("7");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton7ActionPerformed
    /**
    * adds 1 to the adminDisplay
    * @param evt 
    */
    private void numButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton1ActionPerformed
        this.passwordChangeClear();
        this.addToField("1");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton1ActionPerformed
    /**
     * if adminMode toggled, checks the passcode in adminTextField and enables
     * adminMode in the VendingMachine Class. Used to increment drink Quantity
     * @param evt 
     */
    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        if (adminButton.isSelected() && !vmObj.isAdminEnabled())
            this.plusAdminEnterVariant();
        if (vmObj.isPasswordChange() && vmObj.isAdminEnabled())
            this.plusPasswordChangeVariant();
        if(vmObj.isItemSelected() && vmObj.isAdminEnabled()){
            this.plusIncrementVariant();
        }    
    }//GEN-LAST:event_plusButtonActionPerformed
    /**
     * variation of the plus button for entering password
     */
    private void plusAdminEnterVariant(){
        if (!vmObj.isAdminEnabled()) {
            String holder = adminDisplay.getText();
            if (vmObj.isCodeEqual(holder)) {
                vmObj.setAdminEnabled(true);
                this.adminDisplay.setText("success");
            }
            else{
                this.adminDisplay.setText("incorrect");
            }
        }
    }
    /**
     * variation of the plus button for changing password
     */
    private void plusPasswordChangeVariant(){
        if(!reEnter){//first entry
            vmObj.setTempPW(adminDisplay.getText());
            this.adminField = reEnterPrompt;
            this.updateAdminDisplay();
            reEnter = true;
        }
        else if(reEnter){//second entry
            if(vmObj.getTempPW().equals(adminDisplay.getText())){//match
                vmObj.setStoredPW();
                reEnter = false;
                vmObj.setPasswordChange(false);
                this.adminField = "";
                adminDisplay.setText("success!");
            }
            else if(!vmObj.getTempPW().equals(adminDisplay.getText())){
                adminField = "";
                adminDisplay.setText("mismatch");
            }    
        }
    }
    /**
     * increments the selected Item
     */
    private void plusIncrementVariant(){
        vmObj.incrementItemQuantity();
        this.setDisplayToQuantity();
    }
    /**
     * selects the CocoCola item and carries out carries out purchase
     * @param evt 
     */
    private void cocaColaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaColaButton1ActionPerformed
        vmObj.setSelectedItem(0);//Coca-Cola array location
        if(vmObj.getSelectedItem() == 0)
            vmObj.setIsItemSelected(!vmObj.isItemSelected());
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        }   
    }//GEN-LAST:event_cocaColaButton1ActionPerformed
    /**
    * adds $0.25 to the balance of current purchase
    * @param evt 
    */
    private void addQuart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuart
        vmObj.addQuart();
        this.updateDisplay();
    }//GEN-LAST:event_addQuart
    /**
    * adds 2 to the adminDisplay
    * @param evt 
    */
    private void numButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton2ActionPerformed
        this.passwordChangeClear();
        this.addToField("2");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton2ActionPerformed
    /**
    * adds 3 to the adminDisplay
    * @param evt 
    */
    private void numButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton3ActionPerformed
        this.passwordChangeClear();
        this.addToField("3");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton3ActionPerformed
    /**
    * adds 4 to the adminDisplay
    * @param evt 
    */
    private void numButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton4ActionPerformed
        this.passwordChangeClear();
        this.addToField("4");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton4ActionPerformed
    /**
    * adds 5 to the adminDisplay
    * @param evt 
    */
    private void numButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton5ActionPerformed
        this.passwordChangeClear();
        this.addToField("5");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton5ActionPerformed
    /**
    * adds 6 to the adminDisplay
    * @param evt 
    */
    private void numButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton6ActionPerformed
        this.passwordChangeClear();
        this.addToField("6");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton6ActionPerformed
    /**
    * adds 8 to the adminDisplay
    * @param evt 
    */
    private void numButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton8ActionPerformed
        this.passwordChangeClear();
        this.addToField("8");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton8ActionPerformed
    /**
    * adds 9 to the adminDisplay
    * @param evt 
    */
    private void numButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton9ActionPerformed
        this.passwordChangeClear();
        this.addToField("9");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton9ActionPerformed
    /**
    * adds 0 to the adminDisplay
    * @param evt 
    */
    private void numButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numButton0ActionPerformed
        this.passwordChangeClear();
        this.addToField("0");
        this.updateAdminDisplay();
    }//GEN-LAST:event_numButton0ActionPerformed
    /**
     * can be used to delete a digit of the entered passcode or decrement
     * the quantity of a item if admin mode is toggled
     * @param evt 
     */
    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        if(!vmObj.isItemSelected())
            this.deleteFromField();
        if(vmObj.isItemSelected() && vmObj.isAdminEnabled()){
            vmObj.decrementItemQuantity();
            this.setDisplayToQuantity();
        }   
    }//GEN-LAST:event_minusButtonActionPerformed
    /**
     * adds a Dollar to the balance
     * @param evt 
     */
    private void addDollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDollarActionPerformed
        if(!vmObj.isAdminEnabled()){
            vmObj.addDollar();
            this.updateDisplay();
        }
        else if(vmObj.isAdminEnabled()){
            this.changePasswordVariant();
        }           
    }//GEN-LAST:event_addDollarActionPerformed
    /**
     * variant of the addDollar button that activates the password change
     * process if the admin mode has been toggled in the vmObj class
     */
    private void changePasswordVariant(){
        if(!vmObj.isPasswordChange()){
            vmObj.setPasswordChange(true);
            this.adminField = changePrompt;
            this.updateAdminDisplay();
        }
    }
    /**
     * selects the CocoCola item and carries out carries out purchase
     * @param evt 
     */
    private void cocaColaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaColaButton2ActionPerformed
        vmObj.setSelectedItem(0);//Coca-Cola array location
        if(vmObj.getSelectedItem() == 0)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        }   
    }//GEN-LAST:event_cocaColaButton2ActionPerformed
    /**
     * selects the Coke Zero item and carries out carries out purchase
     * @param evt 
     */
    private void cokeZeroButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeZeroButton1ActionPerformed
        vmObj.setSelectedItem(1);//Coke Zero array Location
        if(vmObj.getSelectedItem() == 1)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_cokeZeroButton1ActionPerformed
    /**
     * selects the Coke Zero item and carries out carries out purchase
     * @param evt 
     */
    private void cokeZeroButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeZeroButton2ActionPerformed
        vmObj.setSelectedItem(1);//Coke Zero array Location
        if(vmObj.getSelectedItem() == 1)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_cokeZeroButton2ActionPerformed
    /**
     * selects the Diet Coke item and carries out carries out purchase
     * @param evt 
     */
    private void dietCokeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietCokeButton1ActionPerformed
        vmObj.setSelectedItem(2);//Diet Coke array Location
        if(vmObj.getSelectedItem() == 2)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_dietCokeButton1ActionPerformed
    /**
     * selects the Diet Coke item and carries out carries out purchase
     * @param evt 
     */
    private void dietCokeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietCokeButton2ActionPerformed
        vmObj.setSelectedItem(2);//Diet Coke array Location
        if(vmObj.getSelectedItem() == 2)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_dietCokeButton2ActionPerformed
    /**
     * selects the Sprite item and carries out carries out purchase
     * @param evt 
     */
    private void spriteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteButton1ActionPerformed
        vmObj.setSelectedItem(3);//Sprite array Location
        if(vmObj.getSelectedItem() == 3)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_spriteButton1ActionPerformed
    /**
     * selects the Sprite item and carries out carries out purchase
     * @param evt 
     */
    private void spriteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteButton2ActionPerformed
        vmObj.setSelectedItem(3);//Sprite array Location
        if(vmObj.getSelectedItem() == 3)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        }
    }//GEN-LAST:event_spriteButton2ActionPerformed
    /**
     * selects the Powerade item and carries out carries out purchase
     * @param evt 
     */
    private void poweradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poweradeButtonActionPerformed
        vmObj.setSelectedItem(4);//powerade array Location
        if(vmObj.getSelectedItem() == 4)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_poweradeButtonActionPerformed
    /**
     * selects the Mt. Dew item and carries out carries out purchase
     * @param evt 
     */
    private void mtDewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtDewButtonActionPerformed
        vmObj.setSelectedItem(5);//Mt. Dew array Location
        if(vmObj.getSelectedItem() == 5)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_mtDewButtonActionPerformed
    /**
     * selects the Vitamin Water item and carries out carries out purchase
     * @param evt 
     */
    private void vitaWaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitaWaterButtonActionPerformed
        vmObj.setSelectedItem(6);//Vitamin Water array Location
        if(vmObj.getSelectedItem() == 6)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_vitaWaterButtonActionPerformed
    /**
     * selects the Dasani item and carries out carries out purchase
     * @param evt 
     */
    private void dasaniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasaniButtonActionPerformed
        vmObj.setSelectedItem(7);//Vitamin Water array Location
        if(vmObj.getSelectedItem() == 7)
            vmObj.setIsItemSelected(true);
        if(!vmObj.isAdminEnabled()){//carries out purchase 
            vmObj.makePurchase();
            this.updateDisplay();
        }
        if(vmObj.isAdminEnabled()){//admin quantity change display
            this.setDisplayToQuantity();
        } 
    }//GEN-LAST:event_dasaniButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton addDollar;
    private javax.swing.JButton addQuartButton;
    private javax.swing.JToggleButton adminButton;
    private javax.swing.JTextField adminDisplay;
    private javax.swing.JButton cocaColaButton1;
    private javax.swing.JButton cocaColaButton2;
    private javax.swing.JButton cokeZeroButton1;
    private javax.swing.JButton cokeZeroButton2;
    private javax.swing.JButton dasaniButton;
    private javax.swing.JButton dietCokeButton1;
    private javax.swing.JButton dietCokeButton2;
    private javax.swing.JTextField display;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton mtDewButton;
    private javax.swing.JButton numButton0;
    private javax.swing.JButton numButton1;
    private javax.swing.JButton numButton2;
    private javax.swing.JButton numButton3;
    private javax.swing.JButton numButton4;
    private javax.swing.JButton numButton5;
    private javax.swing.JButton numButton6;
    private javax.swing.JButton numButton7;
    private javax.swing.JButton numButton8;
    private javax.swing.JButton numButton9;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton poweradeButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton spriteButton1;
    private javax.swing.JButton spriteButton2;
    private javax.swing.JButton vitaWaterButton;
    // End of variables declaration//GEN-END:variables
}
